name: PHPUnit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql-server:
        image: mysql:9.2
        env:
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_name_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2 & XDebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        id: composer-install
        # if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      # - name: Xdebug Action
      #   uses: MilesChou/docker-xdebug@master:8.2

      - name: Run test suite
        id: phpunit
        env:
          JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          XDEBUG_MODE: "coverage"
        run: |
          mkdir var;
          chmod +x bin/phpunit;
          echo "${{ secrets.PUBLICA }}" >| ./config/public.pem;
          echo "${{ secrets.PRIVADA }}" >| ./config/private.pem;
          bin/phpunit -dxdebug.mode=coverage

      - name: Run mutation tests suite for added (A) and modified (M) files
        id: mutation-tests
        env:
          JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          XDEBUG_MODE: "coverage"
        run: |
          chmod +x bin/infection;
          bin/infection --ansi --coverage="var/coverage" --threads=20 --only-covered --logger-github
